### ISSUE TITLE
Message above Menu: <span class="nice-menu-show-title">test</span>

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/nice_menus#1]
backdrop Version 1.0.1,
Thema bartik.
After putting the primary menu in the header block the text "<span class="nice-menu-show-title">test</span>" is displayed above the menu.
Look at opi.vtadtest.de

**Comment by docwilmot** [comment]
Hi, Nice Menus is a block, so it has a title. You need to go into the configuration and set the title from 'default' to 'none'.
But thanks for the report; I've fixed the HTML and changed the title from test to the menu name as it should have been.
